name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install depenedencies
      run: npm install
    - name: Start server
      run: npm run server &
    - name: Start FE
      run: npm run start &
    - name: Execute tests
      run: npm run test