name: Build, test and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - name: Install depenedencies
      run: npm install
    - name: Install Playright
      run: npx playwright install
    - name: Replace host url
      run: echo "export default 'http://localhost:3030'" > src/api/host.js
    - name: Start server
      run: npm run server &
    - name: Start FE
      run: npm run start &
    - name: Execute tests
      run: npm run test

  deploy_be:
    needs: build_test

    runs-on: ubuntu-latest

    steps:
    - name: Deploy app to render.com
      uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.SERVICE_ID }}
        api_key: ${{ secrets.RENDER_ID }}
        wait_deploy: true

  deploy_fe:
    needs: build_test

    runs-on: ubuntu-latest

    steps:
    - name: Deploy app to render.com
      uses: actions/checkout@v3
    - uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.SERVICE_FE_ID }}
        api_key: ${{ secrets.RENDER_ID }}
        wait_deploy: true